channels:
- conda-forge
dependencies:
- python=3.8.20
- pip<=23.0.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.1
  - imbalanced-learn==0.12.4
  - numpy==1.24.4
  - psutil==7.0.0
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
